name: Mac_CI

on:
  push:
    branches:
    - main
    - rel-*
  pull_request:
    branches:
    - main
    - rel-*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  python_version: 3.13
  xcode_version: 16

jobs:
  ARM64:
    runs-on: macos-latest

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python_version }}

    - name: Use Xcode ${{ env.xcode_version }}
      shell: bash
      run: |
        XCODE_DEVELOPER_DIR="/Applications/Xcode_${{ env.xcode_version }}.app/Contents/Developer"
        sudo xcode-select --switch "${XCODE_DEVELOPER_DIR}"

    - uses: actions/checkout@v4

    - name: Build and test
      shell: bash
      run: |
        bash ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=arm64 --use_coreml --use_xcode --skip_tests
        mkdir -p ./upload
        find . -name "*.dylib" -exec cp {} ./upload \;

    - name: Upload ARM64 build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arm64-build
        path: ./upload
