name: Mac_CI

on:
  push:
    branches:
    - jicwen/coreml_fp16
    - rel-*
  pull_request:
    branches:
    - jicwen/coreml_fp16
    - rel-*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  python_version: 3.11
  xcode_version: 15.2

jobs:
  ARM64:
    runs-on: macos-latest

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python_version }}

    - name: Use Xcode ${{ env.xcode_version }}
      shell: bash
      run: |
        XCODE_DEVELOPER_DIR="/Applications/Xcode_${{ env.xcode_version }}.app/Contents/Developer"
        sudo xcode-select --switch "${XCODE_DEVELOPER_DIR}"

    - uses: actions/checkout@v4

    - name: Build and test
      shell: bash
      run: |
        python ./tools/ci_build/build.py \
          --build_dir ./build \
          --update \
          --build --parallel \
          --test \
          --build_shared_lib \
          --build_objc \
          --use_coreml \
          --use_xnnpack \
          --use_binskim_compliant_compile_flags
        mkdir -p ./upload
        find . -name "*.dylib" -exec cp {} ./upload \;

    - name: Upload ARM64 build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arm64-build
        path: ./upload
